.PHONY: chat

chat:
	@echo "Opening chat terminal..."
	gnome-terminal -- python3 chat.py

test:
	@echo "Opening three chat terminals..."
	gnome-terminal -- python3 chat.py &
	gnome-terminal -- python3 chat.py &
	gnome-terminal -- python3 chat.py &
